# Generated by Django 5.2 on 2025-04-25 03:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PerfilCandidato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='fotos_candidatos/')),
                ('descripcion', models.TextField()),
                ('educacion', models.TextField()),
                ('experiencia', models.TextField()),
                ('habilidades', models.TextField()),
                ('curriculum', models.FileField(blank=True, null=True, upload_to='curriculums/')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
