# Generated by Django 5.2 on 2025-04-25 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCandidatos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfilcandidato',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='fotos_candidato/'),
        ),
    ]
