# Generated by Django 5.2 on 2025-04-25 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppEmpresas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PerfilEmpresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos/')),
                ('descripcion', models.TextField()),
                ('correo_contacto', models.EmailField(max_length=254)),
                ('sector', models.CharField(max_length=100)),
                ('tamano', models.CharField(max_length=50)),
                ('sitio_web', models.URLField(blank=True)),
            ],
        ),
    ]
