# Generated by Django 5.2 on 2025-04-25 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppEmpresas', '0002_perfilempresa'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilempresa',
            name='direccion',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='perfilempresa',
            name='telefono',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
